### ISSUE TITLE
Update URLs in readme.md & Google Play listing

### ISSUE THREAD

**Issue by alanthehat** [DarkRealmGaming/AndroidSudo#3]
Few of the links are still working  in https://github.com/DarkRealmGaming/AndroidSudo/blob/master/README.md and https://play.google.com/store/apps/details?id=com.darkrealmgaming.androidsudo

**Comment by alanthehat** [comment]
In particular the Gingerbread variant is not accessible

**Comment by ColtonDRG** [comment]
Yes, I have been neglecting that for a while. Sorry about that. I'll dig up the old versions and upload them.

**Comment by alanthehat** [comment]
Thank you :-)

**Comment by ColtonDRG** [comment]
Little update: I can only find the latest version, so unfortunately I can't upload the GB version right now. That said, I did find the signing keys I used to generate the APK, so I can recompile the old version, which I will do in a few days.

**Comment by ColtonDRG** [comment]
Just updated the readme. I'll update the Play Store listing soon.

**Comment by alanthehat** [comment]
I understand that it's possible to store binaries here in Github?

**Comment by ColtonDRG** [comment]
It is. I forgot about that. I'll use that function on the next release.
